### ISSUE TITLE
No CI

### ISSUE THREAD

**Issue by maxgerhardt** [Megunolink/MLP#14]
This repo doesn't use Github Actions at all to check the compilability of the library against different Arduino cores.

PlatformIO or arduino-cli can be used for this very easily.

**Comment by PaulMartinsen** [comment]
Yes. This is a very good idea as soon as we can figure out how and get the time to do it! Watch this space...

Thanks for the suggestion.

**Comment by PaulMartinsen** [comment]
I've added [Adafruit's ci-arduino](https://github.com/adafruit/ci-arduino) tests to the repository to check compatibility against a variety of cores. This proved to be both very straight forward and identified a few build problems that have been fixed to make the library more reliable. 

Thanks again for the suggestion @maxgerhardt. Much appreciated.
