### ISSUE TITLE
warning: 'prog_char' is deprecated: prog_char type is deprecated.

### ISSUE THREAD

**Issue by damienfieldhouse** [Megunolink/MLP#6]
This is no longer working for me and when i upload the code to my Nano I get the error messages:

In file included from C:\Users\damie\Documents\Arduino\libraries\MLP-master\utility\StreamParser.h:4:0,
                 from C:\Users\damie\Documents\Arduino\libraries\MLP-master\utility\StreamParser.cpp:1:
C:\Users\damie\Documents\Arduino\libraries\MLP-master\utility\CommandDispatcherBase.h:10:11: warning: 'prog_char' is deprecated: prog_char type is deprecated. [-Wdeprecated-declarations]
     PGM_P m_strCommand;
           ^~~~~~~~~~~~

**Comment by PaulMartinsen** [comment]
That's a warning, not an error. It shouldn't prevent your program working. 
* What version of the Arduino IDE are you using? 
* What does "no longer working" mean?

**Comment by PaulMartinsen** [comment]
The latest release of the library has removed dependence on __PROG_TYPES_COMPAT__, which caused these warnings.
