### ISSUE TITLE
Arduino Nano Every (ATmega4809) compatibility issue

### ISSUE THREAD

**Issue by Ichibot200** [Megunolink/MLP#7]
I am facing trouble with compiling the CommandHandler for Arduino Nano Every.
I get a bunch of errors:
<details><summary>CLICK HERE FOR COMPILATION LOG!</summary>
<p>

    Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino: In function 'void setup()':

    MyNanoEveryProgram:93:54: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("CWST"), Cmd_CWST);

                                                          ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    MyNanoEveryProgram:94:56: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("CCWST"), Cmd_CCWST);

                                                            ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    MyNanoEveryProgram:96:54: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("MVCW"), Cmd_MVCW);

                                                          ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    MyNanoEveryProgram:98:56: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("MVCCW"), Cmd_MVCCW);

                                                            ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    MyNanoEveryProgram:99:62: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("SetSpeed"), Cmd_SetSpeed);

                                                                  ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    MyNanoEveryProgram:100:56: error: no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

       SerialCommandHandler.AddCommand(F("HELLO"), Cmd_HELLO);

                                                            ^

    In file included from F:\Users\USER\Documents\Arduino\libraries\MegunoLink/CommandHandler.h:6:0,

                     from Y:\MyNanoEveryProgram\MyNanoEveryProgram.ino:1:

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note: candidate: bool MLP::CommandDispatcherBase::AddCommand(const arduino::__FlashStringHelper*, void (*)(CommandParameter&))

         bool AddCommand(const __FlashStringHelper *pCommand, void(*CallbackFunction)(CommandParameter &rParameters));

              ^~~~~~~~~~

    F:\Users\USER\Documents\Arduino\libraries\MegunoLink/utility/CommandDispatcherBase.h:40:10: note:   no known conversion for argument 1 from 'const char*' to 'const arduino::__FlashStringHelper*'

    Using library MegunoLink at version 1.25 in folder: F:\Users\USER\Documents\Arduino\libraries\MegunoLink 
    exit status 1
    no matching function for call to 'CommandHandler<>::AddCommand(const char*, void (&)(CommandParameter&))'

</p>
</details>

From what I can tell, that the main issue is conversions from ```'const char*' to 'const arduino::__FlashStringHelper*'```

**Comment by PaulMartinsen** [comment]
It does look like Arduino Nano Every is not using __FlashStringHelper when you put the command name inside F("..."). However, I can't tell why. 

Would you mind compiling the "HandleSerialCommands" example for the Arduino Nano Every to see if that has the same problem please? You can find this example in the Arduino IDE by selecting: File &rarr; Examples &rarr; MegunoLink &rarr; Command Handler &rarr; HandleSerialCommands. This example builds for me for the Arduino Nano Every using version 1.8.13 of the Arduino IDE. 

Could you also check which version of the MegunoLink library you are using please? You'll find this on the second line of  `F:\Users\USER\Documents\Arduino\libraries\MegunoLink\library.properties`

**Comment by Ichibot200** [comment]
I found the culprit.
I am using Arduino IDE 1.8.12 and in that, I installed megaAVR boards package (version 1.8.6). In this package there is this file:
C:\Users\USER\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.6\cores\arduino\Arduino.h

Deleting (or commenting out) lines 29-31:
```c

#undef F
#define F(str) (str)

```
allows a successful compilation.

Reference: https://github.com/arduino/ArduinoCore-megaavr/commit/a0f6beb55e6c60fdd7baffb306d99c0844377f43

**Comment by PaulMartinsen** [comment]
Good find. Thanks for the update. I'll close this since it is outside the scope of our library.
